FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /server ./cmd/main.go

FROM alpine:3.19
COPY --from=builder /server /server
EXPOSE 8083
ENTRYPOINT ["/server"]
