"""
RCIR v8.1 — High-Recall Candidate Generator (PHASES 5, 8, 10).

Generates a broad candidate pool from multiple orthogonal sources with strict feature gating:
- Exact entity lookup (conditional on use_entity_resolution)
- Boundary route / event graph (conditional on use_boundary_graph)
- Policy-controlled graph expansion (conditional on use_traversal)
- Lexical matches (conditional on use_lexical)
- Verification / test graph (conditional on use_test_graph)
- Historical co-change (conditional on use_historical)

Preserves rich edge evidence, resolution classes, and minimum supported hop distance.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

from rcir.entities.registry import EntityRegistry
from rcir.entities.resolver import EntityResolver
from rcir.graph.multi_view import MultiViewGraph
from rcir.graph.traversal_policy import TraversalPolicy, execute_policy_traversal
from rcir.query.change_spec import ChangeSpecification
from rcir.retrieval.scorer import TFIDFScorer


@dataclass
class CandidateGeneratorConfig:
    """Explicit configuration switches for ablation control (PHASE 10)."""
    use_entity_resolution: bool = True
    use_boundary_graph: bool = True
    use_test_graph: bool = True
    use_lexical: bool = True
    use_traversal: bool = True
    use_historical: bool = False
    lexical_top_k: int = 40


@dataclass
class CandidateRecord:
    """A single candidate generated by one or more retrieval sources (PHASE 8)."""
    entity_id: str
    file_path: str
    candidate_sources: list[str] = field(default_factory=list)
    graph_paths: list[list[str]] = field(default_factory=list)
    best_hop_distance: int = 0
    edge_evidence: list[dict[str, Any]] = field(default_factory=list)
    best_traversal_score: float = 0.0
    resolution_classes: list[str] = field(default_factory=list)
    edge_types_seen: list[str] = field(default_factory=list)
    raw_lexical_score: float = 0.0

    @property
    def hop_distance(self) -> int:
        return self.best_hop_distance

    @hop_distance.setter
    def hop_distance(self, val: int) -> None:
        self.best_hop_distance = val

    def to_dict(self) -> dict[str, Any]:
        return {
            "entity_id": self.entity_id,
            "file_path": self.file_path,
            "candidate_sources": list(self.candidate_sources),
            "graph_paths": self.graph_paths,
            "best_hop_distance": self.best_hop_distance,
            "best_traversal_score": round(self.best_traversal_score, 4),
            "resolution_classes": self.resolution_classes,
            "edge_types_seen": self.edge_types_seen,
            "edge_evidence": self.edge_evidence,
        }


class CandidateGenerator:
    """Multi-source candidate generator producing an unranked candidate pool."""

    def __init__(
        self,
        multi_view: MultiViewGraph,
        registry: EntityRegistry | None = None,
        scorer: TFIDFScorer | None = None,
        config: CandidateGeneratorConfig | None = None,
    ):
        self.multi_view = multi_view
        self.registry = registry or EntityRegistry.from_graph(multi_view.raw_graph)
        self.resolver = EntityResolver(self.registry)
        self.scorer = scorer
        self.config = config or CandidateGeneratorConfig()

    def generate(
        self,
        spec: ChangeSpecification,
        policy: TraversalPolicy | None = None,
        config_override: CandidateGeneratorConfig | None = None,
    ) -> list[CandidateRecord]:
        """Generate candidates across all enabled sources for the given change specification."""
        cfg = config_override or self.config
        candidates_map: dict[str, CandidateRecord] = {}

        def get_or_create(node_id: str, source: str) -> CandidateRecord:
            file_part = node_id.split("::")[0].replace("\\", "/").strip("/") if "::" in node_id else node_id.replace("\\", "/").strip("/")
            if node_id not in candidates_map:
                candidates_map[node_id] = CandidateRecord(
                    entity_id=node_id,
                    file_path=file_part,
                    candidate_sources=[source],
                )
            else:
                if source not in candidates_map[node_id].candidate_sources:
                    candidates_map[node_id].candidate_sources.append(source)
            return candidates_map[node_id]

        seed_entities: list[str] = []

        # Source 1: Entity Lookup (Entity resolution active vs disabled)
        for target in spec.target_entities:
            target_clean = target.replace("\\", "/").strip("/")

            # File match in registry
            if self.registry:
                for ent in self.registry.by_file.get(target_clean, []):
                    rec = get_or_create(ent.entity_id, "exact_entity_lookup")
                    rec.best_hop_distance = 0
                    seed_entities.append(ent.entity_id)
                    if "::" in ent.entity_id:
                        parts = ent.entity_id.split("::")
                        seed_entities.append(parts[1])
                        if len(parts) > 2:
                            seed_entities.append(f"{parts[1]}::{parts[2]}")

            # Symbol match in registry
            sym = target.split("::")[-1].split("/")[-1]
            if self.registry and cfg.use_entity_resolution:
                for ent in self.registry.lookup_name(sym):
                    rec = get_or_create(ent.entity_id, "exact_entity_lookup")
                    rec.best_hop_distance = 0
                    seed_entities.append(ent.entity_id)
                    if "::" in ent.entity_id:
                        parts = ent.entity_id.split("::")
                        seed_entities.append(parts[1])
                        if len(parts) > 2:
                            seed_entities.append(f"{parts[1]}::{parts[2]}")

            # Companion event detection in same directory
            if "Events" in target_clean and "/" in target_clean:
                dir_path = "/".join(target_clean.split("/")[:-1])
                if self.registry:
                    for f_path, f_ents in self.registry.by_file.items():
                        if f_path.startswith(dir_path):
                            for ent in f_ents:
                                if "Event" in ent.name:
                                    rec = get_or_create(ent.entity_id, "companion_entity")
                                    rec.best_hop_distance = 0
                                    seed_entities.append(ent.entity_id)
                                    if "::" in ent.entity_id:
                                        seed_entities.append(ent.entity_id.split("::")[1])

            if cfg.use_entity_resolution:
                res = self.resolver.resolve(target)
                if res.resolved_entity:
                    rec = get_or_create(res.resolved_entity.entity_id, "exact_entity_lookup")
                    rec.best_hop_distance = 0
                    seed_entities.append(res.resolved_entity.entity_id)
                elif res.exact_matches:
                    for ent in res.exact_matches:
                        rec = get_or_create(ent.entity_id, "exact_entity_lookup")
                        rec.best_hop_distance = 0
                        seed_entities.append(ent.entity_id)
                elif res.ambiguous_candidates:
                    for ent in res.ambiguous_candidates[:5]:
                        rec = get_or_create(ent.entity_id, "ambiguous_entity_lookup")
                        rec.best_hop_distance = 0
                        seed_entities.append(ent.entity_id)

            # Direct node / file lookup
            if target in self.multi_view.node_by_path:
                rec = get_or_create(target, "exact_node_lookup")
                rec.best_hop_distance = 0
                seed_entities.append(target)

            for npath in self.multi_view.node_by_path:
                if target_clean in npath or npath == target_clean:
                    rec = get_or_create(npath, "exact_file_lookup")
                    rec.best_hop_distance = 0
                    seed_entities.append(npath)

        # Source 2: Boundary Graph (routes, events, frontend-to-route)
        if cfg.use_boundary_graph:
            for target in spec.target_entities:
                clean_sym = target.split("::")[-1].split("/")[-1]
                routes = self.multi_view.get_routes_for_controller(clean_sym)
                for r in routes:
                    src = r.get("source", "")
                    tgt = r.get("target", "")
                    rec_src = get_or_create(src, "boundary_graph")
                    rec_tgt = get_or_create(tgt, "boundary_graph")
                    rec_src.edge_types_seen.append("route")
                    rec_tgt.edge_types_seen.append("route")
                    seed_entities.extend([src, tgt])

        # Source 3: Policy-Controlled Traversal
        if cfg.use_traversal and seed_entities:
            active_policy = policy or TraversalPolicy.for_operation(spec.operation, seed_degree=len(seed_entities))
            unique_seeds = list(dict.fromkeys(seed_entities))
            hits = execute_policy_traversal(self.multi_view, unique_seeds, active_policy)
            for hit in hits:
                rec = get_or_create(hit.node_id, "policy_traversal")
                if rec.best_hop_distance == 0 or hit.best_hop_distance < rec.best_hop_distance:
                    rec.best_hop_distance = hit.best_hop_distance
                if hit.best_traversal_score > rec.best_traversal_score:
                    rec.best_traversal_score = hit.best_traversal_score
                for p in hit.paths:
                    rec.graph_paths.append(p)
                for ev in hit.edge_evidence:
                    rec.edge_evidence.append(ev.to_dict())
                for rc in hit.resolution_classes:
                    if rc not in rec.resolution_classes:
                        rec.resolution_classes.append(rc)
                for et in hit.edge_types:
                    if et not in rec.edge_types_seen:
                        rec.edge_types_seen.append(et)

        # Source 4: Lexical (TF-IDF / BM25)
        if cfg.use_lexical and self.scorer and spec.description:
            for node_path, score in self.scorer.top_k(spec.description, k=cfg.lexical_top_k):
                rec = get_or_create(node_path, "lexical_tfidf")
                rec.raw_lexical_score = score

        # Source 5: Verification / Test Graph
        if cfg.use_test_graph:
            for seed in list(dict.fromkeys(seed_entities)):
                test_edges = self.multi_view.get_tests_for_entity(seed)
                for te in test_edges:
                    test_src = te.get("source", "")
                    if test_src:
                        rec = get_or_create(test_src, "test_graph")
                        rec.edge_types_seen.append("source_to_test")

        return list(candidates_map.values())
