"""
RCIR v8 — High-Recall Candidate Generator (PHASE 8).

Generates a broad candidate pool from multiple orthogonal sources:
- Exact entity lookup
- Direct graph edges
- Policy-controlled graph expansion
- TF-IDF / lexical matches
- Boundary route / event graph
- Verification / test graph

Keeps candidate generation strictly separated from ranking and context selection.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from rcir.entities.registry import EntityRegistry
from rcir.entities.resolver import EntityResolver
from rcir.graph.multi_view import MultiViewGraph
from rcir.graph.traversal_policy import TraversalPolicy, execute_policy_traversal
from rcir.query.change_spec import ChangeSpecification
from rcir.retrieval.scorer import TFIDFScorer


@dataclass
class CandidateRecord:
    """A single candidate generated by one or more retrieval sources."""
    entity_id: str
    file_path: str
    candidate_sources: list[str] = field(default_factory=list)
    graph_paths: list[list[str]] = field(default_factory=list)
    hop_distance: int = 0
    raw_lexical_score: float = 0.0
    edge_types_seen: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "entity_id": self.entity_id,
            "file_path": self.file_path,
            "candidate_sources": list(self.candidate_sources),
            "graph_paths": self.graph_paths,
            "hop_distance": self.hop_distance,
        }


class CandidateGenerator:
    """Multi-source candidate generator producing an unranked candidate pool."""

    def __init__(
        self,
        multi_view: MultiViewGraph,
        registry: EntityRegistry | None = None,
        scorer: TFIDFScorer | None = None,
    ):
        self.multi_view = multi_view
        self.registry = registry or EntityRegistry.from_graph(multi_view.raw_graph)
        self.resolver = EntityResolver(self.registry)
        self.scorer = scorer

    def generate(
        self,
        spec: ChangeSpecification,
        policy: TraversalPolicy | None = None,
        include_lexical: bool = True,
        lexical_top_k: int = 40,
    ) -> list[CandidateRecord]:
        """Generate candidates across all available sources for the given change specification."""
        candidates_map: dict[str, CandidateRecord] = {}

        def get_or_create(node_id: str, source: str) -> CandidateRecord:
            file_part = node_id.split("::")[0].replace("\\", "/").strip("/") if "::" in node_id else node_id.replace("\\", "/").strip("/")
            if node_id not in candidates_map:
                candidates_map[node_id] = CandidateRecord(
                    entity_id=node_id,
                    file_path=file_part,
                    candidate_sources=[source],
                )
            else:
                if source not in candidates_map[node_id].candidate_sources:
                    candidates_map[node_id].candidate_sources.append(source)
            return candidates_map[node_id]

        seed_entities: list[str] = []

        # Source 1: Exact Entity Lookup
        for target in spec.target_entities:
            res = self.resolver.resolve(target)
            if res.resolved_entity:
                rec = get_or_create(res.resolved_entity.entity_id, "exact_entity_lookup")
                rec.hop_distance = 0
                seed_entities.append(res.resolved_entity.entity_id)
            elif res.exact_matches:
                for ent in res.exact_matches:
                    rec = get_or_create(ent.entity_id, "exact_entity_lookup")
                    rec.hop_distance = 0
                    seed_entities.append(ent.entity_id)
            elif res.ambiguous_candidates:
                # Add ambiguous candidates with caution
                for ent in res.ambiguous_candidates[:5]:
                    rec = get_or_create(ent.entity_id, "ambiguous_entity_lookup")
                    rec.hop_distance = 0
                    seed_entities.append(ent.entity_id)

            # Also check if target is a file or in node_by_path directly
            if target in self.multi_view.node_by_path:
                rec = get_or_create(target, "exact_node_lookup")
                rec.hop_distance = 0
                seed_entities.append(target)

            target_norm = target.replace("\\", "/").strip("/")
            for npath in self.multi_view.node_by_path:
                if target_norm in npath or npath == target_norm:
                    rec = get_or_create(npath, "exact_file_lookup")
                    rec.hop_distance = 0
                    seed_entities.append(npath)

        # Source 2: Boundary Graph (routes, events, frontend-to-route)
        for target in spec.target_entities:
            clean_sym = target.split("::")[-1].split("/")[-1]

            # Route matches
            routes = self.multi_view.get_routes_for_controller(clean_sym)
            for r in routes:
                src = r.get("source", "")
                tgt = r.get("target", "")
                rec_src = get_or_create(src, "boundary_graph")
                rec_tgt = get_or_create(tgt, "boundary_graph")
                rec_src.edge_types_seen.append("route")
                rec_tgt.edge_types_seen.append("route")
                seed_entities.extend([src, tgt])

        # Source 3: Policy-Controlled Traversal
        active_policy = policy or TraversalPolicy.for_operation(spec.operation)
        if seed_entities:
            unique_seeds = list(dict.fromkeys(seed_entities))
            hits = execute_policy_traversal(self.multi_view, unique_seeds, active_policy)
            for hit in hits:
                rec = get_or_create(hit.node_id, "policy_traversal")
                rec.hop_distance = max(rec.hop_distance, hit.hop_distance)
                rec.graph_paths.append(hit.path)
                rec.edge_types_seen.append(hit.edge_type)

        # Source 4: Lexical (TF-IDF)
        if include_lexical and self.scorer and spec.description:
            for node_path, score in self.scorer.top_k(spec.description, k=lexical_top_k):
                rec = get_or_create(node_path, "lexical_tfidf")
                rec.raw_lexical_score = score

        # Source 5: Verification / Test Graph
        for seed in list(seed_entities):
            test_edges = self.multi_view.get_tests_for_entity(seed)
            for te in test_edges:
                test_src = te.get("source", "")
                if test_src:
                    rec = get_or_create(test_src, "test_graph")
                    rec.edge_types_seen.append("source_to_test")

        return list(candidates_map.values())
